make sure we fail if any command inside update fails
Change-Id: I89f42d9097b5f47b149ab3a45c23e35fd7f39172

diff --git a/update b/update
--- a/update
+++ b/update
@@ -1,14 +1,21 @@
+# Make sure we fail if any single command fails!
+set -e -u
+
 echo -e "\n### update yeti code"
 git pull
+
 echo -e "\n### update yeti submodule, i.e. assets"
 git submodule update --init --recursive
+
 echo -e "\n### bundle install ruby gems"
-ext_opt=$1
+ext_opt=${1:-local}
+
 if [[ $ext_opt = 'ci' ]]
 then
   bundle install
 else
   bundle install --without ci
 fi
+
 echo -e "\n### sync pre-compiled java apps"
 rake sync_assets
